input {
  beats {
      port => 5044
  }
}
filter {
    date {
      match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSS"] #将匹配到的日期 赋值到es指定字段
      target => "@timestamp"
    }
}
output {
  elasticsearch {
      hosts => "es01:9200"
      index => "gjq-demo-log-%{+YYYY.MM.dd}"
  }
}

