#创建用户表
USE test;
CREATE TABLE `a_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_name` VARCHAR(255) NOT NULL COMMENT '用户名',
  `user_pwd` VARCHAR(255) NOT NULL COMMENT '用户密码',
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;