server:
    port: 9090

# springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        - group: 'default'
          display-name: '基础信息管理'
          paths-to-match: '/**'
          packages-to-scan: com.iot.mqtt.business.basic.controller
        - group: 'eqp-group'
          display-name: '设备管理'
          paths-to-match: '/**'
          packages-to-scan: com.iot.mqtt.business.eqp.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
    enable: true
    setting:
        language: zh_cn
        swagger-model-name: 实体类列表
    documents:
      - name: 开发文档说明
        locations: classpath:markdown/*
        group: 基础信息管理
      - name: 测试文档说明
        locations: classpath:markdown2/*
        group: 基础信息管理
    #访问API页面认证
    basic:
      enable: false
      username: abc
      password: 123