server:
    port: 5670

logging:
  file:
    path: ./logs
    name: app-demo.log
  level:
    root: info
    com:
      gjw:
        go:
          job:
            one: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{100}.%M:%L - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


spring:
  application:
    name: go-demo
  profiles:
    active: local

