server:
  port: 9999

# https://docs.spring.io/spring-ai/reference/1.0/api/mcp/mcp-client-boot-starter-docs.html
spring:
  ai:
    mcp:
      client:
        enabled: true # 是否启用MCP客户端,默认：true
        request-timeout: 60s # MCP客户端请求超时时间,默认：20s
        type: SYNC # MCP客户端类型,默认：SYNC(同步)
        name: call-mcp-server # MCP客户端名称,默认：spring-ai-mcp-client
        stdio:
          servers-configuration: classpath:mcp-server.json
        # SSE配置
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8080
    # 通义大模型配置
    dashscope:
      api-key: sk-4bb06acbc78146aabbef23a1a8d94339
      chat:
        options:
          model: qwen-max