server:
  port: 9090
gjw:
  user-name: xxxx
  password: 111111

logging:
  level:
    com.baomidou.mybatisplus: DEBUG

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_flow?characterEncoding=utf8&useSSL=false
    username: root
    password: tiger
mybatis-plus:
  configuration:
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl