input {
    file {
        path => ["/logs/*.log"]
        tags => "go-app"
        add_field => {
            log_type => "one"
        }
    }
}
filter {
    if [log_type] == "one" {
        mutate {
            add_field => {
                "[@metadata][target_index]" => "go-app-%{+YYYY.MM.dd}"
            }
        }
    } else {
        mutate {
            add_field => {
                "[@metadata][target_index]" => "unknown-%{+YYYY.MM.dd}"
            }
        }
    }
    # 是@timestamp的值使用日志中匹配到的时间值
    #深入理解 ELK 中 Logstash 的底层原理 + 填坑指南 https://server.51cto.com/article/710561.html
    #Kibana 自带 grok 的正则匹配的工具 http://127.0.0.1:5601/app/dev_tools#/grokdebugger
    grok{
        match => {"message" => "(?<logTime>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3})"}
    }
    date {
      match => ["logTime", "yyyy-MM-dd HH:mm:ss.SSS"]
      timezone => "Asia/Shanghai"
      target => "@timestamp"
    }
}
output {
    stdout {}
    elasticsearch {
        hosts => "es01:9200"
        index => "%{[@metadata][target_index]}"
    }
}

