version: '3'

networks:
  elk:
    external: true

services:
  es:
    image: elasticsearch:8.4.3
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - elk
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./es/config:/usr/share/elasticsearch/config
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/logs:/usr/share/elasticsearch/logs