version: '3'

networks:
  elk:
    external: true

services:
  logstash:
    image: logstash:8.4.3
    container_name: logstash
    ports:
      - "9600:9600"
      - "5044:5044"
      - "4560:4560"
    restart: always
    networks:
      - elk
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline