##############################################
#       系统配置
##############################################
server:
  port: 9999 #服务端口号设置
app:
  version: @project.version@ #项目的版本信息
spring:
  profiles:
    include: redis