############################################################
# REDIS 配置
############################################################
spring:
  redis:
    database: 0
    host: 192.168.137.150
    port: 6379
    password:
    timeout: 6000  # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接