package rules

import java.util.*
import java.time.*
import com.gjw.go.common.utils.*
import com.gjw.go.domain.dto.Intval
//规则2：100元-500元 加100分

global List<Intval> intvalList;

rule "score_3"
    when
        Intval(
           $days:getDay(),
           $interval:getInterval(),
           $eqpMaintRuleGenerateId:getGenerateId()
        )
        eval(($days - $eqpMaintRuleGenerateId) >= ($interval * 0.8))
    then
        Long eqpMaintRuleGenerateId = new Double(($days + ($interval * 0.2)) - (($days + ($interval * 0.2)) % $interval)).longValue();

        System.out.println("执行 "+$days +" GenerateId=" +eqpMaintRuleGenerateId);
        intvalList.add(Intval.instance($days,$interval,eqpMaintRuleGenerateId));
end